apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: actividad-semana-6
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
