apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: josephalmonte/app1:latest  # Asegúrate de que esta imagen esté disponible en Docker Hub y que cualquier imagen privada pueda ser accedida con las credenciales proporcionadas
        ports:
        - containerPort: 8081
        env:
        - name: RABBITMQ_URL
          value: "amqp://joseph:1192948@rabbitmq1:5673/"
      imagePullSecrets:
      - name: regcred
