apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: actividad-semana-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: josephalmonte/app2:latest
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: regcred
